apiVersion: v1
entries:
  fastapi-hello:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-01-13T15:54:05.352490582Z"
    description: A Hello world app for Kubernetes
    digest: 7af7f4e228f1246a0a04f1c8c9b31398e02c7b6db43a230fafd625c752840693
    name: fastapi-hello
    type: application
    urls:
    - https://jerilseb.github.io/charts/fastapi-hello-1.0.4.tgz
    version: 1.0.4
  jupyterlab:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-01-13T15:54:05.353064115Z"
    description: A Helm chart for JupyterLab
    digest: 7b21ba5e32ef8c9558cbfd33ecf6126135bf1f17ff76057a60f7e96fa1d300f5
    name: jupyterlab
    type: application
    urls:
    - https://jerilseb.github.io/charts/jupyterlab-1.0.4.tgz
    version: 1.0.4
  spot-termination-handler:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-01-13T15:54:05.353247936Z"
    description: A simple Helm chart for an EC2 termination handler
    digest: 40b794fef956c893a2b34bfddc073dc2c44578507a259c6f002c7f8aa81ad61b
    name: spot-termination-handler
    urls:
    - https://jerilseb.github.io/charts/spot-termination-handler-1.0.1.tgz
    version: 1.0.1
generated: "2025-01-13T15:54:05.35093334Z"
